project:
  type: website

website:
  title: "FormationR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "R for beginners"
        href: rforbeginer.qmd
      - text: "Graph"
        href: Graph.qmd
      - text: "Satistics"
        href: Statitics.qmd
    right:
      - icon: github
        href: https://github.com/marcgarel/FormationR.github.io
  page-footer:
      center: |
        [![](/img/logo-cnrs.jpg){fig-alt="CNRS" height=40px}](https://www.cnrs.fr//)
        [![](/img/Logo_IRD_2016_BLOC_FR_COUL.png ){fig-alt="IRD" height=40px}](https://www.ird.fr/)
        [![](/img/logo_fr_mio_rvb_small.jpg){fig-alt="MIO" height=40px}](https://www.mio.osupytheas.fr/)
        [![](/img/logoAMU.png){fig-alt="AMU" height=40px}](https://www.univ-amu.fr/)
        [![](/img/OSU-IP_RVB_H100_ECRAN.jpg){fig-alt="OSU" height=30px}](https://osupytheas.fr/)
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



