project:
  type: website

website:
  title: "FormationR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "R for beginners"
        href: rforbeginer.qmd
    right:
      - icon: github
        href: https://github.com/marcgarel/FormationR.github.io
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



