---
title: "FormationR"
---

Welcome on the R training provided by [OMICS](https://www.mio.osupytheas.fr/fr/plateformes-de-recherche/ptf-omics) platform and [MIO](https://www.mio.osupytheas.fr/fr)


## Schedule 

* **DAY1** : 
  * [Rstudio](courses/Intro_R_Rstudio_2023.pdf) environment and R language course 
  * Practical 1: R basics: Vectors, Tables, dataframe, manipulations, descriptive statistics, Rmarkdown
  
* **DAY2**
  * End of Practical 1
  * [Graphical](courses/GGplot_mg.pdf) representation of biological data & management of parameters type/colour/shape/...
  
* **DAY3**
  * Practical 2 Graphical representation of results
  
* **DAY4**
  * Lectures and practical work: Inferential statistics (Anova, Kruskall, Wilcoxon, regression, correlation, r, R2, adjusted p-value, etc.)
  
* **Day 5**
  * Global test - Validation of prior learning
  
  ##Useful documents
  
  In this section you can find some cheatsheet for some important packages : 
  
  * [dplyr](docs/data-transformation_dplyr-1.pdf)
  * [ggplo2](docs/data-visualization_ggplot2-2.1.pdf)
  * [rmarkdown](docs/rmarkdown-2.0.pdf)
  



